version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=pos_user
      - DB_PASSWORD=1234
      - DB_NAME=pos
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./app.py:/app/app.py
    depends_on:
      - mysql
    command: python app.py

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pos
      - MYSQL_USER=pos_user
      - MYSQL_PASSWORD=1234
    ports:
      - "3307:3306"  # Expose port for local development
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql

volumes:
  mysql_data:
    driver: local
